### ISSUE TITLE
Install FAILS with python3.12 on Ubuntu 22.04

### ISSUE THREAD

**Issue by DavCisco** [fbradyirl/webex_bot#53]
ubuntu@webexlab:~$ pip install webex_bot
Defaulting to user installation because normal site-packages is not writeable
Collecting webex_bot
  Using cached webex_bot-0.4.1-py2.py3-none-any.whl.metadata (10 kB)
Collecting webexteamssdk==1.6.1 (from webex_bot)
  Using cached webexteamssdk-1.6.1-py3-none-any.whl.metadata (8.0 kB)
Collecting coloredlogs (from webex_bot)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting websockets==10.2 (from webex_bot)
  Using cached websockets-10.2.tar.gz (83 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ubuntu@webexlab:~$ 
ubuntu@webexlab:~$ python3 -V
Python 3.12.2
ubuntu@webexlab:~$ pip -V
pip 24.0 from /home/ubuntu/.local/lib/python3.12/site-packages/pip (python 3.12)
ubuntu@webexlab:~$ 

ubuntu@webexlab:~$ neofetch
            .-/+oossssoo+/-.                                                                                                                                                              
        `:+ssssssssssssssssss+:`           --------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.4 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: VMware Virtual Platform None 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-101-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 20 hours, 14 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 669 (dpkg), 4 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16

**Comment by gconklin** [comment]
3.12 not supported, see https://github.com/fbradyirl/webex_bot/issues/44#issuecomment-1816904758

use 3.11
